name: publish docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - "nubank-v*.*.*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Define variables
        id: publish_vars
        run: |
          IMG="${{github.repository}}"
          TAG=${{ env.REGISTRY }}/${IMG}:${GITHUB_REF_NAME}
          echo "TAG=${TAG}" >> ${GITHUB_OUTPUT}
          echo "CACHE_TAG=${TAG}-buildcache" >> ${GITHUB_OUTPUT}
          SHA="${GITHUB_SHA:0:8}"
          echo "SHA=${SHA}" >> ${GITHUB_OUTPUT}
      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.publish_vars.outputs.TAG }}
          build-args: |
            SOURCE_COMMIT=${{ steps.publish_vars.outputs.SHA }}
          cache-from: type=registry,ref=${{ steps.publish_vars.outputs.CACHE_TAG }}
          cache-to: type=registry,ref=${{ steps.publish_vars.outputs.CACHE_TAG }},mode=max
